# Copyright (c) 2019 Ant Financial
#
# SPDX-License-Identifier: Apache-2.0
#

dist: bionic
os: linux

# set cache directories manually, because
# we are using a non-standard directory struct
# cargo root is in srs/agent
#
# If needed, caches can be cleared
# by ways documented in
# https://docs.travis-ci.com/user/caching#clearing-caches
language: rust
rust:
  - 1.47.0
cache:
  cargo: true
  directories:
    - src/agent/target

before_install:
  - git remote set-branches --add origin "${TRAVIS_BRANCH}"
  - git fetch
  - export RUST_BACKTRACE=1
  - export target_branch=$TRAVIS_BRANCH
  - "ci/setup.sh"

# we use install to run check agent
# so that it is easy to skip for non-amd64 platform
install:
  - export PATH=$PATH:"$HOME/.cargo/bin"
  - export RUST_AGENT=yes
  - rustup target add arm64-unknown-linux-musl
  - sudo ln -sf /usr/bin/g++ /bin/musl-g++
  - rustup component add rustfmt
  - rustup component add clippy
  - make -C ${TRAVIS_BUILD_DIR}/src/agent clippy
  - "ci/static-checks.sh"

before_script:
  - "ci/install_go.sh"
  - make -C ${TRAVIS_BUILD_DIR}/src/runtime
  - make -C ${TRAVIS_BUILD_DIR}/src/runtime test
  - sudo apt-get install -y golang-go
  - sudo -E PATH=$PATH GOPATH=$GOPATH make -C ${TRAVIS_BUILD_DIR}/src/runtime test

script:
  - make -C ${TRAVIS_BUILD_DIR}/src/agent
  - make -C ${TRAVIS_BUILD_DIR}/src/agent check
  - sudo -E PATH=$PATH make -C ${TRAVIS_BUILD_DIR}/src/agent check

jobs:
  include:
  - name: arm64 test
    arch: arm64
    os: linux
    install: skip
    script: skip
  allow_failures:
    - name: arm64 test
  fast_finish: true
